swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains available API endpoints for Phase 2
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

# Définition des endpoints (chemins d'accès aux API)
paths:
  /user/transactions/currentMonth:
    get:
      # Définition du schéma de sécurité (Bearer token nécessaire pour accéder à l'API)
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API to view user's current month's transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User's current month's transactions retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponseTransactions"
        "400":
          description: Transactions not found
        "500":
          description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API to view one user's transaction by id
      operationId: getTransactionById
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User's transaction retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponseTransactionId"
        "400":
          description: Transaction not found
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for updating one user's transaction by id
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update one user's transaction
          required: true
          schema:
            $ref: "#/definitions/UpdateTransactionId"
      produces:
        - application/json
      responses:
        "200":
          description: User's transaction retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponseTransactionId"
        "400":
          description: Invalid Fields or Transaction not found
        "500":
          description: Internal Server Error

# Définition du schéma de sécurité (Bearer token dans l'en-tête)
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

# Définition des schémas de données
definitions:
  ApiResponseTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            accountUser:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            balance:
              type: number
            transactionType:
              type: string
            category:
              type: string
            notes:
              type: string
  ApiResponseTransactionId:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          accountUser:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
  UpdateTransactionId:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
